# archive.py
import os
from typing import List, Optional, Union
import requests
from tqdm import tqdm
from datetime import datetime


ROWS_PER_PAGE = 100
BASE_SEARCH_URL = "https://archive.org/advancedsearch.php"
METADATA_URL = "https://archive.org/metadata"
DOWNLOAD_BASE = "https://archive.org/download"
HEADERS = {"User-Agent": "archive-downloader (educational use)"}


def build_search_query(
    text="",
    subjects=None,
    genres=None,
    year_from=None,
    year_to=None,
    artist=None
):
    """
    Build a search query string for the Internet Archive audio collection.

    This function composes a query string combining free text, subject filters,
    genres, date ranges, and artist name into a single AND-separated query
    compatible with the Internet Archive search API.

    Parameters
    ----------
    text : str, optional
        Free text search query.
    subjects : Union[str, List[str]], optional
        Subject tags to filter by. Can be a comma-separated string or list.
    genres : Union[str, List[str]], optional
        Genres to filter by. Combined with OR inside the subject field.
    year_from : str, optional
        Start year (inclusive). If only this is provided, range is [year_from TO *].
    year_to : str, optional
        End year (inclusive). If only this is provided, range is [* TO year_to].
    artist : str, optional
        Artist/creator name. Case-insensitive (lowercased internally).

    Returns
    -------   
    str
        Fully constructed query string ready to be sent to the search API.
    """
    def normalize(v):
        """Normalize input into a list of strings."""
        if not v:
            return []
        if isinstance(v, str):
            return [x.strip() for x in v.split(",") if x.strip()]
        return v

    def or_block(field, values):
        """Build an OR query block for a field."""
        if not values:
            return None
        values = [f'"{v}"' if " " in v else v for v in values]
        return f"{field}:({' OR '.join(values)})"

    parts = []

    if text:
        parts.append(text)

    subjects = normalize(subjects)
    genres = normalize(genres)

    parts += [f'subject:"{s}"' for s in subjects]

    for block in [or_block("subject", genres)]:
        if block:
            parts.append(block)

    parts += [
        "mediatype:audio",
        "collection:audio_music",
    ]

    if year_from or year_to:
        yf = year_from or "*"
        yt = year_to or "*"
        parts.append(f"year:[{yf} TO {yt}]")

    if artist:
        parts.append(f'creator:("{artist.lower()}")')

    return " AND ".join(parts)


def search_items(page, query):
    """
    Perform a search request against the Internet Archive API.

    Parameters
    ----------
    page : int
        Page number of results to retrieve.
    query : str
        Query string generated by `build_search_query`.

    Returns
    -------
    dict
        The "response" section of the API JSON result, containing items and metadata.

    Raises
    ------
    requests.HTTPError
        If the HTTP request fails.
    """
    params = {
        "q": query,
        "fl[]": "identifier",
        "rows": ROWS_PER_PAGE,
        "page": page,
        "output": "json",
    }
    r = requests.get(BASE_SEARCH_URL, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()["response"]

def get_mp3_files(identifier):
    """
    Retrieve all MP3 filenames for a given Internet Archive item.

    Parameters
    ----------
    identifier : str
        Internet Archive item identifier.

    Returns
    -------
    list of str
        List of MP3 filenames available for the item.

    Raises
    ------
    requests.HTTPError
        If the metadata request fails.
    """
    r = requests.get(f"{METADATA_URL}/{identifier}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    data = r.json()

    mp3s = []
    for f in data.get("files", []):
        name = f.get("name", "")
        if name.lower().endswith(".mp3"):
            mp3s.append(name)
    return mp3s

def download_mp3(identifier, filename, dest_dir):
    """
    Download an MP3 file from the Internet Archive.

    Parameters
    ----------
    identifier : str
        Internet Archive item identifier.
    filename : str
        Name of the MP3 file to download.
    dest_dir : str
        Local directory where the file will be stored.

    Returns
    -------
    str or None
        Path to the downloaded file, or None if the download failed.

    Raises
    ------
    requests.HTTPError
        If the HTTP request fails and is not handled.
    """
    url = f"{DOWNLOAD_BASE}/{identifier}/{filename}"
    local_path = os.path.join(dest_dir, filename)

    if os.path.exists(local_path):
        return local_path # already downloaded

    os.makedirs(dest_dir, exist_ok=True)
    with requests.get(url, stream=True, headers=HEADERS, timeout=60) as r:
        try:
            r.raise_for_status()
        except requests.exceptions.HTTPError as e:
            print(f"❌ Error downloading {filename}: {e}")
            return None
        total = int(r.headers.get("content-length", 0))

        with open(local_path, "wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=filename,
            leave=False,
        ) as bar:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    bar.update(len(chunk))
    return local_path
